### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by Nepooomuk** [pheanex/cs1.6config#1]
dear mr pheanex,

könnten sie bitte ein versionsupgrade herbei führen?

ich kann verstehen dass sie mit dem jahr 2000 aufgrund ihrer seitdem fortwährenden sexuellen enthaltsamkeit viel positives verbinden, allerdings sollten sie zukunftsgewandt nach vorn schauen(mit cs go).

kisses,
doktor sommer

**Comment by pheanex** [comment]
Tut mir leid, ein Versionsupgrade wäre leider keine "saubere Lösung".
